services:
  - type: web
    name: ice-cream-backend
    plan: free
    runtime: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
